//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PV_RPT.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCountry
    {
        public long CountryId { get; set; }
        public string Code { get; set; }
        public string CountryName { get; set; }
        public string MobileCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
